# Generated by Django 2.0.3 on 2020-06-22 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={},
        ),
    ]
